name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies (CPU-only PyTorch)
        run: |
          python -m pip install --upgrade pip
          # Install CPU-only PyTorch to avoid heavy CUDA wheels on CI
          pip install --index-url https://download.pytorch.org/whl/cpu torch torchvision -r requirements.txt
          pip install -r requirements-dev.txt
        env:
          PIP_CACHE_DIR: ${{ runner.temp }}/pip-cache
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Run tests
        run: |
          export PYTHONPATH=$(pwd)/src
          pytest -q
